[build]
  command = "pip install -r requirements.txt"
  publish = "templates"
  functions = "functions"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 